name: workflow1
on: 
  push:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: run a single command on ubuntu machine
        run: hostname
      - name: step2
        run: |
          echo "Running step 2"
          sleep 5
          hostname
      - name: step3
        run: |
          echo "Running step 3"
          sleep 5
          hostname
