name: second_workflow
on: 
  push:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: run a single command on ubuntu machine on second workflow
        run: hostname
      - name: step2
        run: |
          echo "Running step 2 on second workflow job 1"
          sleep 5
          hostname
      - name: step3
        run: |
          echo "Running step 3 on second workflow job 1"
          sleep 5
          hostname
